-- This is an empty migration.

-- Enable RLS for tables

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."VendorProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."City" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OrganizerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Listing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BookingRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."VerificationRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AdminLog" ENABLE ROW LEVEL SECURITY;